server:
  port: 8080

spring:
  mustache:
    expose-session-attributes: true
  datasource:
      url: jdbc:h2:mem:test
      driver-class-name: org.h2.Driver
      username: sa
      password: 

  jpa: 
    hibernate:
      ddl-auto: create
      